### ISSUE TITLE
Request for Personal Information Removal

### ISSUE THREAD

**Issue by sylvanding** [Patrick-orz/LoveRecord#1]

**Comment by Patrick-orz** [comment]
Thank you for reaching out to me on this issue.

I completely understand your situation. I wanted to use your repo as a template and edit it for myself, but didn't have the chance to do so yet.

I went with option 2, and if there are any remaining information you would like edited or removed, please tell me. By the way, by checking commit logs the information would still visible, if you want me to take down the repo entirely, I would be fine with it as well.

This issue would be closed until further comments from you ❤️.

@sylvanding
